import { z, registry } from '../../lib/registry';
import {
  IncidentStatus,
  IncidentSeverity,
  IncidentType,
} from './incident.enums';

export const createIncidentSchema = registry.register(
  'CreateIncidentRequest',
  z.object({
    title: z
      .string({
        error: ({ input }) =>
          input === undefined
            ? 'O título do incidente é obrigatório.'
            : 'O título deve ser um texto.',
      })
      .min(3, { message: 'Título muito curto.' })
      .max(150, { message: 'Título muito longo.' })
      .trim()
      .openapi({
        description: 'Título curto descrevendo o problema',
        example: 'Falha de comunicação com o Gateway de Pagamento',
      }),

    incidentRef: z.string().trim().nullable().optional().openapi({
      description: 'Código de referência externa (ex: INC-2026-0013)',
    }),

    serviceId: z
      .string()
      .uuid({ message: 'O ID do serviço deve ser um UUID válido.' })
      .nullable()
      .optional()
      .openapi({
        description:
          'UUID do serviço afetado. Se nulo, afeta a infraestrutura global.',
      }),

    type: z.nativeEnum(IncidentType).default(IncidentType.OTHER).openapi({
      description: 'Categoria/tipo de incidente',
      example: IncidentType.OUTAGE,
    }),

    severity: z.nativeEnum(IncidentSeverity).openapi({
      description: 'Nível de impacto do incidente',
      example: IncidentSeverity.MAJOR_OUTAGE,
    }),

    status: z
      .nativeEnum(IncidentStatus)
      .default(IncidentStatus.INVESTIGATING)
      .openapi({
        description: 'Fase atual de tratamento do incidente',
        example: IncidentStatus.INVESTIGATING,
      }),

    isAutoGenerated: z.boolean().default(false).openapi({
      description:
        'Indica se foi detectado/aberto automaticamente pela telemetria',
      example: false,
    }),

    httpStatus: z.number().int().nullable().optional().openapi({
      description: 'Código de resposta HTTP quando aplicável',
      example: 502,
    }),

    errorDetails: z.string().nullable().optional().openapi({
      description: 'Detalhes ou traceback da falha detectada',
      example: 'ECONNREFUSED 192.168.1.50:5001',
    }),

    startedAt: z.coerce.date().optional().openapi({
      description: 'Data e hora exata em que o incidente começou',
    }),

    resolvedAt: z.coerce.date().nullable().optional().openapi({
      description: 'Data e hora em que o incidente foi resolvido',
    }),

    durationMinutes: z.number().int().nullable().optional().openapi({
      description: 'Duração total do incidente em minutos',
    }),
  }),
);

export const updateIncidentSchema = registry.register(
  'UpdateIncidentRequest',
  createIncidentSchema
    .partial()
    .refine((data) => Object.keys(data).length > 0, {
      message: 'Pelo menos um campo deve ser fornecido para atualização.',
    }),
);

export const incidentResponseSchema = registry.register(
  'IncidentResponse',
  z.object({
    id: z.string().uuid(),
    title: z.string(),
    incidentRef: z.string().nullable(),
    serviceId: z.string().uuid().nullable(),
    type: z.nativeEnum(IncidentType),
    severity: z.nativeEnum(IncidentSeverity),
    status: z.nativeEnum(IncidentStatus),
    isAutoGenerated: z.boolean(),
    httpStatus: z.number().nullable().optional(),
    errorDetails: z.string().nullable().optional(),
    startedAt: z.date(),
    resolvedAt: z.date().nullable(),
    durationMinutes: z.number().nullable(),
    createdAt: z.date(),
    updatedAt: z.date(),
  }),
);

export const incidentPublicResponseSchema = registry.register(
  'IncidentPublicResponse',
  z.object({
    id: z.string().uuid(),
    serviceId: z.string().uuid().nullable().optional(),
    title: z.string(),
    type: z.nativeEnum(IncidentType),
    status: z.nativeEnum(IncidentStatus),
    severity: z.nativeEnum(IncidentSeverity),
    isAutoGenerated: z.boolean().optional(),
    httpStatus: z.number().nullable().optional(),
    startedAt: z.date(),
    resolvedAt: z.date().nullable().optional(),
    durationMinutes: z.number().int().nullable().optional(),
    incidentRef: z.string().nullable(),
    service: z
      .object({
        name: z.string(),
        slug: z.string(),
      })
      .nullable()
      .optional(),
  }),
);

export const incidentIdSchema = z.object({
  id: z
    .string()
    .uuid({
      error: ({ input }) =>
        input === undefined
          ? 'O ID é obrigatório.'
          : 'O ID do incidente deve ser um UUID válido.',
    })
    .openapi({
      param: {
        name: 'id',
        in: 'path',
      },
      description: 'UUID Identificador exclusivo do incidente',
    }),
});
