import { describe, it, expect } from 'vitest';
import {
  createIncidentSchema,
  IncidentSeverity,
  IncidentStatus,
  IncidentType,
} from '../../../src/modules/incident';

describe('Incident Schemas Unit Tests', () => {
  it('should validate valid incident creation with IncidentType', () => {
    const payload = {
      title: 'Queda do Servidor Web',
      type: IncidentType.OUTAGE,
      severity: IncidentSeverity.MAJOR_OUTAGE,
      status: IncidentStatus.INVESTIGATING,
      isAutoGenerated: true,
      httpStatus: 502,
      errorDetails: 'Connection refused',
    };

    const parsed = createIncidentSchema.safeParse(payload);
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect(parsed.data.type).toBe('OUTAGE');
      expect(parsed.data.isAutoGenerated).toBe(true);
      expect(parsed.data.httpStatus).toBe(502);
    }
  });

  it('should apply default IncidentType.OTHER when not specified', () => {
    const payload = {
      title: 'Incidente sem categoria explícita',
      severity: IncidentSeverity.DEGRADED,
    };

    const parsed = createIncidentSchema.safeParse(payload);
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect(parsed.data.type).toBe(IncidentType.OTHER);
      expect(parsed.data.isAutoGenerated).toBe(false);
    }
  });
});
